<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Coupon;
use Carbon\Carbon;

class CouponSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $coupons = [
            // ========== BRONZE LEVEL (6 mã) ==========
            [
                'name' => 'Mã Giảm Giá Bronze - 5%',
                'code' => 'BRONZE5',
                'description' => 'Giảm giá 5% cho khách hàng Bronze',
                'discount_type' => 'percentage',
                'discount_value' => 5,
                'min_order_value' => 2000000,
                'max_discount' => 100000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addMonths(6),
                'validity_days' => 30,
                'exchange_points' => 5000,
                'vip_level' => 'Bronze',
                'status' => 1,
                'usage_limit' => 1000,
                'used_count' => 0,
            ],
            [
                'name' => 'Mã Giảm Giá Bronze - 8%',
                'code' => 'BRONZE8',
                'description' => 'Giảm giá 8% cho khách hàng Bronze',
                'discount_type' => 'percentage',
                'discount_value' => 8,
                'min_order_value' => 3000000,
                'max_discount' => 200000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addMonths(6),
                'validity_days' => 30,
                'exchange_points' => 8000,
                'vip_level' => 'Bronze',
                'status' => 1,
                'usage_limit' => 800,
                'used_count' => 0,
            ],
            [
                'name' => 'Mã Giảm Giá Bronze - 10%',
                'code' => 'BRONZE10',
                'description' => 'Giảm giá 10% cho khách hàng Bronze',
                'discount_type' => 'percentage',
                'discount_value' => 10,
                'min_order_value' => 5000000,
                'max_discount' => 300000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addMonths(6),
                'validity_days' => 30,
                'exchange_points' => 12000,
                'vip_level' => 'Bronze',
                'status' => 1,
                'usage_limit' => 500,
                'used_count' => 0,
            ],
            [
                'name' => 'Mã Giảm Tiền Bronze - 100K',
                'code' => 'BRONZE100K',
                'description' => 'Giảm tiền 100,000đ cho khách hàng Bronze',
                'discount_type' => 'fixed',
                'discount_value' => 100000,
                'min_order_value' => 1500000,
                'max_discount' => 100000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addMonths(6),
                'validity_days' => 30,
                'exchange_points' => 6000,
                'vip_level' => 'Bronze',
                'status' => 1,
                'usage_limit' => 1000,
                'used_count' => 0,
            ],
            [
                'name' => 'Mã Giảm Tiền Bronze - 200K',
                'code' => 'BRONZE200K',
                'description' => 'Giảm tiền 200,000đ cho khách hàng Bronze',
                'discount_type' => 'fixed',
                'discount_value' => 200000,
                'min_order_value' => 3000000,
                'max_discount' => 200000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addMonths(6),
                'validity_days' => 30,
                'exchange_points' => 10000,
                'vip_level' => 'Bronze',
                'status' => 1,
                'usage_limit' => 800,
                'used_count' => 0,
            ],
            [
                'name' => 'Mã Giảm Tiền Bronze - 300K',
                'code' => 'BRONZE300K',
                'description' => 'Giảm tiền 300,000đ cho khách hàng Bronze',
                'discount_type' => 'fixed',
                'discount_value' => 300000,
                'min_order_value' => 5000000,
                'max_discount' => 300000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addMonths(6),
                'validity_days' => 30,
                'exchange_points' => 15000,
                'vip_level' => 'Bronze',
                'status' => 1,
                'usage_limit' => 500,
                'used_count' => 0,
            ],

            // ========== SILVER LEVEL (6 mã) ==========
            [
                'name' => 'Mã Giảm Giá Silver - 10%',
                'code' => 'SILVER10',
                'description' => 'Giảm giá 10% cho khách hàng Silver',
                'discount_type' => 'percentage',
                'discount_value' => 10,
                'min_order_value' => 3000000,
                'max_discount' => 200000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addMonths(6),
                'validity_days' => 30,
                'exchange_points' => 8000,
                'vip_level' => 'Silver',
                'status' => 1,
                'usage_limit' => 800,
                'used_count' => 0,
            ],
            [
                'name' => 'Mã Giảm Giá Silver - 12%',
                'code' => 'SILVER12',
                'description' => 'Giảm giá 12% cho khách hàng Silver',
                'discount_type' => 'percentage',
                'discount_value' => 12,
                'min_order_value' => 5000000,
                'max_discount' => 300000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addMonths(6),
                'validity_days' => 30,
                'exchange_points' => 12000,
                'vip_level' => 'Silver',
                'status' => 1,
                'usage_limit' => 600,
                'used_count' => 0,
            ],
            [
                'name' => 'Mã Giảm Giá Silver - 15%',
                'code' => 'SILVER15',
                'description' => 'Giảm giá 15% cho khách hàng Silver',
                'discount_type' => 'percentage',
                'discount_value' => 15,
                'min_order_value' => 8000000,
                'max_discount' => 500000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addMonths(6),
                'validity_days' => 30,
                'exchange_points' => 18000,
                'vip_level' => 'Silver',
                'status' => 1,
                'usage_limit' => 400,
                'used_count' => 0,
            ],
            [
                'name' => 'Mã Giảm Tiền Silver - 200K',
                'code' => 'SILVER200K',
                'description' => 'Giảm tiền 200,000đ cho khách hàng Silver',
                'discount_type' => 'fixed',
                'discount_value' => 200000,
                'min_order_value' => 2000000,
                'max_discount' => 200000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addMonths(6),
                'validity_days' => 30,
                'exchange_points' => 10000,
                'vip_level' => 'Silver',
                'status' => 1,
                'usage_limit' => 800,
                'used_count' => 0,
            ],
            [
                'name' => 'Mã Giảm Tiền Silver - 300K',
                'code' => 'SILVER300K',
                'description' => 'Giảm tiền 300,000đ cho khách hàng Silver',
                'discount_type' => 'fixed',
                'discount_value' => 300000,
                'min_order_value' => 4000000,
                'max_discount' => 300000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addMonths(6),
                'validity_days' => 30,
                'exchange_points' => 15000,
                'vip_level' => 'Silver',
                'status' => 1,
                'usage_limit' => 600,
                'used_count' => 0,
            ],
            [
                'name' => 'Mã Giảm Tiền Silver - 500K',
                'code' => 'SILVER500K',
                'description' => 'Giảm tiền 500,000đ cho khách hàng Silver',
                'discount_type' => 'fixed',
                'discount_value' => 500000,
                'min_order_value' => 8000000,
                'max_discount' => 500000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addMonths(6),
                'validity_days' => 30,
                'exchange_points' => 25000,
                'vip_level' => 'Silver',
                'status' => 1,
                'usage_limit' => 400,
                'used_count' => 0,
            ],

            // ========== GOLD LEVEL (6 mã) ==========
            [
                'name' => 'Mã Giảm Giá Gold - 15%',
                'code' => 'GOLD15',
                'description' => 'Giảm giá 15% cho khách hàng Gold',
                'discount_type' => 'percentage',
                'discount_value' => 15,
                'min_order_value' => 5000000,
                'max_discount' => 300000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addMonths(6),
                'validity_days' => 30,
                'exchange_points' => 15000,
                'vip_level' => 'Gold',
                'status' => 1,
                'usage_limit' => 600,
                'used_count' => 0,
            ],
            [
                'name' => 'Mã Giảm Giá Gold - 18%',
                'code' => 'GOLD18',
                'description' => 'Giảm giá 18% cho khách hàng Gold',
                'discount_type' => 'percentage',
                'discount_value' => 18,
                'min_order_value' => 8000000,
                'max_discount' => 500000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addMonths(6),
                'validity_days' => 30,
                'exchange_points' => 20000,
                'vip_level' => 'Gold',
                'status' => 1,
                'usage_limit' => 400,
                'used_count' => 0,
            ],
            [
                'name' => 'Mã Giảm Giá Gold - 20%',
                'code' => 'GOLD20',
                'description' => 'Giảm giá 20% cho khách hàng Gold',
                'discount_type' => 'percentage',
                'discount_value' => 20,
                'min_order_value' => 12000000,
                'max_discount' => 800000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addMonths(6),
                'validity_days' => 30,
                'exchange_points' => 30000,
                'vip_level' => 'Gold',
                'status' => 1,
                'usage_limit' => 300,
                'used_count' => 0,
            ],
            [
                'name' => 'Mã Giảm Tiền Gold - 300K',
                'code' => 'GOLD300K',
                'description' => 'Giảm tiền 300,000đ cho khách hàng Gold',
                'discount_type' => 'fixed',
                'discount_value' => 300000,
                'min_order_value' => 3000000,
                'max_discount' => 300000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addMonths(6),
                'validity_days' => 30,
                'exchange_points' => 18000,
                'vip_level' => 'Gold',
                'status' => 1,
                'usage_limit' => 600,
                'used_count' => 0,
            ],
            [
                'name' => 'Mã Giảm Tiền Gold - 500K',
                'code' => 'GOLD500K',
                'description' => 'Giảm tiền 500,000đ cho khách hàng Gold',
                'discount_type' => 'fixed',
                'discount_value' => 500000,
                'min_order_value' => 6000000,
                'max_discount' => 500000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addMonths(6),
                'validity_days' => 30,
                'exchange_points' => 25000,
                'vip_level' => 'Gold',
                'status' => 1,
                'usage_limit' => 400,
                'used_count' => 0,
            ],
            [
                'name' => 'Mã Giảm Tiền Gold - 800K',
                'code' => 'GOLD800K',
                'description' => 'Giảm tiền 800,000đ cho khách hàng Gold',
                'discount_type' => 'fixed',
                'discount_value' => 800000,
                'min_order_value' => 12000000,
                'max_discount' => 800000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addMonths(6),
                'validity_days' => 30,
                'exchange_points' => 40000,
                'vip_level' => 'Gold',
                'status' => 1,
                'usage_limit' => 300,
                'used_count' => 0,
            ],

            // ========== PLATINUM LEVEL (6 mã) ==========
            [
                'name' => 'Mã Giảm Giá Platinum - 20%',
                'code' => 'PLATINUM20',
                'description' => 'Giảm giá 20% cho khách hàng Platinum',
                'discount_type' => 'percentage',
                'discount_value' => 20,
                'min_order_value' => 8000000,
                'max_discount' => 500000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addMonths(6),
                'validity_days' => 30,
                'exchange_points' => 25000,
                'vip_level' => 'Platinum',
                'status' => 1,
                'usage_limit' => 400,
                'used_count' => 0,
            ],
            [
                'name' => 'Mã Giảm Giá Platinum - 25%',
                'code' => 'PLATINUM25',
                'description' => 'Giảm giá 25% cho khách hàng Platinum',
                'discount_type' => 'percentage',
                'discount_value' => 25,
                'min_order_value' => 12000000,
                'max_discount' => 800000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addMonths(6),
                'validity_days' => 30,
                'exchange_points' => 35000,
                'vip_level' => 'Platinum',
                'status' => 1,
                'usage_limit' => 300,
                'used_count' => 0,
            ],
            [
                'name' => 'Mã Giảm Giá Platinum - 30%',
                'code' => 'PLATINUM30',
                'description' => 'Giảm giá 30% cho khách hàng Platinum',
                'discount_type' => 'percentage',
                'discount_value' => 30,
                'min_order_value' => 20000000,
                'max_discount' => 1500000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addMonths(6),
                'validity_days' => 30,
                'exchange_points' => 50000,
                'vip_level' => 'Platinum',
                'status' => 1,
                'usage_limit' => 200,
                'used_count' => 0,
            ],
            [
                'name' => 'Mã Giảm Tiền Platinum - 500K',
                'code' => 'PLATINUM500K',
                'description' => 'Giảm tiền 500,000đ cho khách hàng Platinum',
                'discount_type' => 'fixed',
                'discount_value' => 500000,
                'min_order_value' => 5000000,
                'max_discount' => 500000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addMonths(6),
                'validity_days' => 30,
                'exchange_points' => 30000,
                'vip_level' => 'Platinum',
                'status' => 1,
                'usage_limit' => 400,
                'used_count' => 0,
            ],
            [
                'name' => 'Mã Giảm Tiền Platinum - 800K',
                'code' => 'PLATINUM800K',
                'description' => 'Giảm tiền 800,000đ cho khách hàng Platinum',
                'discount_type' => 'fixed',
                'discount_value' => 800000,
                'min_order_value' => 10000000,
                'max_discount' => 800000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addMonths(6),
                'validity_days' => 30,
                'exchange_points' => 40000,
                'vip_level' => 'Platinum',
                'status' => 1,
                'usage_limit' => 300,
                'used_count' => 0,
            ],
            [
                'name' => 'Mã Giảm Tiền Platinum - 1.2M',
                'code' => 'PLATINUM1M2',
                'description' => 'Giảm tiền 1,200,000đ cho khách hàng Platinum',
                'discount_type' => 'fixed',
                'discount_value' => 1200000,
                'min_order_value' => 20000000,
                'max_discount' => 1200000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addMonths(6),
                'validity_days' => 30,
                'exchange_points' => 60000,
                'vip_level' => 'Platinum',
                'status' => 1,
                'usage_limit' => 200,
                'used_count' => 0,
            ],

            // ========== DIAMOND LEVEL (6 mã) ==========
            [
                'name' => 'Mã Giảm Giá Diamond - 25%',
                'code' => 'DIAMOND25',
                'description' => 'Giảm giá 25% cho khách hàng Diamond',
                'discount_type' => 'percentage',
                'discount_value' => 25,
                'min_order_value' => 10000000,
                'max_discount' => 800000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addMonths(6),
                'validity_days' => 30,
                'exchange_points' => 30000,
                'vip_level' => 'Diamond',
                'status' => 1,
                'usage_limit' => 300,
                'used_count' => 0,
            ],
            [
                'name' => 'Mã Giảm Giá Diamond - 30%',
                'code' => 'DIAMOND30',
                'description' => 'Giảm giá 30% cho khách hàng Diamond',
                'discount_type' => 'percentage',
                'discount_value' => 30,
                'min_order_value' => 15000000,
                'max_discount' => 1200000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addMonths(6),
                'validity_days' => 30,
                'exchange_points' => 40000,
                'vip_level' => 'Diamond',
                'status' => 1,
                'usage_limit' => 250,
                'used_count' => 0,
            ],
            [
                'name' => 'Mã Giảm Giá Diamond - 35%',
                'code' => 'DIAMOND35',
                'description' => 'Giảm giá 35% cho khách hàng Diamond',
                'discount_type' => 'percentage',
                'discount_value' => 35,
                'min_order_value' => 25000000,
                'max_discount' => 2000000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addMonths(6),
                'validity_days' => 30,
                'exchange_points' => 60000,
                'vip_level' => 'Diamond',
                'status' => 1,
                'usage_limit' => 150,
                'used_count' => 0,
            ],
            [
                'name' => 'Mã Giảm Tiền Diamond - 800K',
                'code' => 'DIAMOND800K',
                'description' => 'Giảm tiền 800,000đ cho khách hàng Diamond',
                'discount_type' => 'fixed',
                'discount_value' => 800000,
                'min_order_value' => 8000000,
                'max_discount' => 800000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addMonths(6),
                'validity_days' => 30,
                'exchange_points' => 35000,
                'vip_level' => 'Diamond',
                'status' => 1,
                'usage_limit' => 300,
                'used_count' => 0,
            ],
            [
                'name' => 'Mã Giảm Tiền Diamond - 1.2M',
                'code' => 'DIAMOND1M2',
                'description' => 'Giảm tiền 1,200,000đ cho khách hàng Diamond',
                'discount_type' => 'fixed',
                'discount_value' => 1200000,
                'min_order_value' => 15000000,
                'max_discount' => 1200000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addMonths(6),
                'validity_days' => 30,
                'exchange_points' => 50000,
                'vip_level' => 'Diamond',
                'status' => 1,
                'usage_limit' => 250,
                'used_count' => 0,
            ],
            [
                'name' => 'Mã Giảm Tiền Diamond - 1.8M',
                'code' => 'DIAMOND1M8',
                'description' => 'Giảm tiền 1,800,000đ cho khách hàng Diamond',
                'discount_type' => 'fixed',
                'discount_value' => 1800000,
                'min_order_value' => 25000000,
                'max_discount' => 1800000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addMonths(6),
                'validity_days' => 30,
                'exchange_points' => 80000,
                'vip_level' => 'Diamond',
                'status' => 1,
                'usage_limit' => 150,
                'used_count' => 0,
            ],
        ];

        foreach ($coupons as $coupon) {
            Coupon::updateOrCreate(
                ['code' => $coupon['code']],
                $coupon
            );
        }

        $this->command->info('30 mã giảm giá mẫu đã được tạo thành công! (6 mã cho mỗi level VIP)');
    }
} 